export const ENDPOINTS = {
  // Public
  HOME: '/home',
  CATEGORIES: '/categories',
  CATEGORY: (slug: string) => `/categories/${slug}`,
  CATEGORY_PRODUCTS: (slug: string) => `/categories/${slug}/products`,
  CATEGORY_BRANDS: (slug: string) => `/categories/${slug}/brands`,
  PRODUCTS: '/products',
  PRODUCT: (slug: string) => `/products/${slug}`,
  PRODUCTS_FEATURED: '/products/featured',
  PRODUCTS_NEW: '/products/new',
  PRODUCTS_ON_SALE: '/products/on-sale',
  PRODUCTS_BRANDS: '/products/brands',
  PRODUCT_RELATED: (slug: string) => `/products/${slug}/related`,
  PROMOTIONS: '/promotions',
  PROMOTION_CURRENT: '/promotions/current',
  PROMOTION: (id: number) => `/promotions/${id}`,
  PAGES: '/pages',
  PAGE: (slug: string) => `/pages/${slug}`,
  SETTINGS: '/settings',
  CONTACT: '/contact',
}

export const ADMIN_ENDPOINTS = {
  LOGIN: '/login',
  LOGOUT: '/logout',
  PROFILE: '/profile',
  PRODUCTS: '/products',
  PRODUCT: (id: number) => `/products/${id}`,
  CATEGORIES: '/categories',
  CATEGORY: (id: number) => `/categories/${id}`,
  PROMOTIONS: '/promotions',
  PROMOTION: (id: number) => `/promotions/${id}`,
  MESSAGES: '/messages',
  MESSAGE_READ: (id: number) => `/messages/${id}/read`,
  MESSAGE_REPLY: (id: number) => `/messages/${id}/reply`,
  PAGES: '/pages',
  PAGE: (id: number) => `/pages/${id}`,
  SETTINGS: '/settings',
  CHANGE_PASSWORD: '/change-password',
}